name: jakobidarko
favicon: null
layout_spectrum: 0.006184400292113423
typography_spectrum: 0.5096370147075504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.59987035789527
  lightness: 0.7742123596835881
  saturation: 0.998953208560124
  rhythmicContrast: 0.22999173239804804
purpose: []
